// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: porker/v2/domain.proto

package porkerv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Violation int32

const (
	Violation_VIOLATION_UNSPECIFIED Violation = 0
)

// Enum value maps for Violation.
var (
	Violation_name = map[int32]string{
		0: "VIOLATION_UNSPECIFIED",
	}
	Violation_value = map[string]int32{
		"VIOLATION_UNSPECIFIED": 0,
	}
)

func (x Violation) Enum() *Violation {
	p := new(Violation)
	*p = x
	return p
}

func (x Violation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Violation) Descriptor() protoreflect.EnumDescriptor {
	return file_porker_v2_domain_proto_enumTypes[0].Descriptor()
}

func (Violation) Type() protoreflect.EnumType {
	return &file_porker_v2_domain_proto_enumTypes[0]
}

func (x Violation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Violation.Descriptor instead.
func (Violation) EnumDescriptor() ([]byte, []int) {
	return file_porker_v2_domain_proto_rawDescGZIP(), []int{0}
}

type VoteState int32

const (
	VoteState_VOTE_STATE_UNSPECIFIED VoteState = 0
	VoteState_VOTE_STATE_HIDE        VoteState = 1
	VoteState_VOTE_STATE_OPEN        VoteState = 2
)

// Enum value maps for VoteState.
var (
	VoteState_name = map[int32]string{
		0: "VOTE_STATE_UNSPECIFIED",
		1: "VOTE_STATE_HIDE",
		2: "VOTE_STATE_OPEN",
	}
	VoteState_value = map[string]int32{
		"VOTE_STATE_UNSPECIFIED": 0,
		"VOTE_STATE_HIDE":        1,
		"VOTE_STATE_OPEN":        2,
	}
)

func (x VoteState) Enum() *VoteState {
	p := new(VoteState)
	*p = x
	return p
}

func (x VoteState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VoteState) Descriptor() protoreflect.EnumDescriptor {
	return file_porker_v2_domain_proto_enumTypes[1].Descriptor()
}

func (VoteState) Type() protoreflect.EnumType {
	return &file_porker_v2_domain_proto_enumTypes[1]
}

func (x VoteState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VoteState.Descriptor instead.
func (VoteState) EnumDescriptor() ([]byte, []int) {
	return file_porker_v2_domain_proto_rawDescGZIP(), []int{1}
}

type DisplayMode int32

const (
	DisplayMode_DISPLAY_MODE_UNSPECIFIED DisplayMode = 0
	DisplayMode_DISPLAY_MODE_POINT       DisplayMode = 1
	DisplayMode_DISPLAY_MODE_TSHIRT      DisplayMode = 2
)

// Enum value maps for DisplayMode.
var (
	DisplayMode_name = map[int32]string{
		0: "DISPLAY_MODE_UNSPECIFIED",
		1: "DISPLAY_MODE_POINT",
		2: "DISPLAY_MODE_TSHIRT",
	}
	DisplayMode_value = map[string]int32{
		"DISPLAY_MODE_UNSPECIFIED": 0,
		"DISPLAY_MODE_POINT":       1,
		"DISPLAY_MODE_TSHIRT":      2,
	}
)

func (x DisplayMode) Enum() *DisplayMode {
	p := new(DisplayMode)
	*p = x
	return p
}

func (x DisplayMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DisplayMode) Descriptor() protoreflect.EnumDescriptor {
	return file_porker_v2_domain_proto_enumTypes[2].Descriptor()
}

func (DisplayMode) Type() protoreflect.EnumType {
	return &file_porker_v2_domain_proto_enumTypes[2]
}

func (x DisplayMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DisplayMode.Descriptor instead.
func (DisplayMode) EnumDescriptor() ([]byte, []int) {
	return file_porker_v2_domain_proto_rawDescGZIP(), []int{2}
}

type Point int32

const (
	Point_POINT_UNSPECIFIED Point = 0
	Point_POINT_0           Point = 1
	Point_POINT_0_5         Point = 2
	Point_POINT_1           Point = 3
	Point_POINT_2           Point = 4
	Point_POINT_3           Point = 5
	Point_POINT_5           Point = 6
	Point_POINT_8           Point = 7
	Point_POINT_13          Point = 8
	Point_POINT_21          Point = 9
	Point_POINT_COFFEE      Point = 100
	Point_POINT_QUESTION    Point = 101
)

// Enum value maps for Point.
var (
	Point_name = map[int32]string{
		0:   "POINT_UNSPECIFIED",
		1:   "POINT_0",
		2:   "POINT_0_5",
		3:   "POINT_1",
		4:   "POINT_2",
		5:   "POINT_3",
		6:   "POINT_5",
		7:   "POINT_8",
		8:   "POINT_13",
		9:   "POINT_21",
		100: "POINT_COFFEE",
		101: "POINT_QUESTION",
	}
	Point_value = map[string]int32{
		"POINT_UNSPECIFIED": 0,
		"POINT_0":           1,
		"POINT_0_5":         2,
		"POINT_1":           3,
		"POINT_2":           4,
		"POINT_3":           5,
		"POINT_5":           6,
		"POINT_8":           7,
		"POINT_13":          8,
		"POINT_21":          9,
		"POINT_COFFEE":      100,
		"POINT_QUESTION":    101,
	}
)

func (x Point) Enum() *Point {
	p := new(Point)
	*p = x
	return p
}

func (x Point) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Point) Descriptor() protoreflect.EnumDescriptor {
	return file_porker_v2_domain_proto_enumTypes[3].Descriptor()
}

func (Point) Type() protoreflect.EnumType {
	return &file_porker_v2_domain_proto_enumTypes[3]
}

func (x Point) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Point.Descriptor instead.
func (Point) EnumDescriptor() ([]byte, []int) {
	return file_porker_v2_domain_proto_rawDescGZIP(), []int{3}
}

type Ballot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Point         Point                  `protobuf:"varint,3,opt,name=point,proto3,enum=porker.v2.Point" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ballot) Reset() {
	*x = Ballot{}
	mi := &file_porker_v2_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ballot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ballot) ProtoMessage() {}

func (x *Ballot) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ballot.ProtoReflect.Descriptor instead.
func (*Ballot) Descriptor() ([]byte, []int) {
	return file_porker_v2_domain_proto_rawDescGZIP(), []int{0}
}

func (x *Ballot) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *Ballot) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Ballot) GetPoint() Point {
	if x != nil {
		return x.Point
	}
	return Point_POINT_UNSPECIFIED
}

type RoomCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	AdminUserId   string                 `protobuf:"bytes,2,opt,name=admin_user_id,json=adminUserId,proto3" json:"admin_user_id,omitempty"`
	VoteState     VoteState              `protobuf:"varint,3,opt,name=vote_state,json=voteState,proto3,enum=porker.v2.VoteState" json:"vote_state,omitempty"`
	Ballots       []*Ballot              `protobuf:"bytes,4,rep,name=ballots,proto3" json:"ballots,omitempty"`
	AutoOpen      bool                   `protobuf:"varint,5,opt,name=auto_open,json=autoOpen,proto3" json:"auto_open,omitempty"`
	DisplayMode   DisplayMode            `protobuf:"varint,6,opt,name=display_mode,json=displayMode,proto3,enum=porker.v2.DisplayMode" json:"display_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCondition) Reset() {
	*x = RoomCondition{}
	mi := &file_porker_v2_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCondition) ProtoMessage() {}

func (x *RoomCondition) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCondition.ProtoReflect.Descriptor instead.
func (*RoomCondition) Descriptor() ([]byte, []int) {
	return file_porker_v2_domain_proto_rawDescGZIP(), []int{1}
}

func (x *RoomCondition) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *RoomCondition) GetAdminUserId() string {
	if x != nil {
		return x.AdminUserId
	}
	return ""
}

func (x *RoomCondition) GetVoteState() VoteState {
	if x != nil {
		return x.VoteState
	}
	return VoteState_VOTE_STATE_UNSPECIFIED
}

func (x *RoomCondition) GetBallots() []*Ballot {
	if x != nil {
		return x.Ballots
	}
	return nil
}

func (x *RoomCondition) GetAutoOpen() bool {
	if x != nil {
		return x.AutoOpen
	}
	return false
}

func (x *RoomCondition) GetDisplayMode() DisplayMode {
	if x != nil {
		return x.DisplayMode
	}
	return DisplayMode_DISPLAY_MODE_UNSPECIFIED
}

var File_porker_v2_domain_proto protoreflect.FileDescriptor

const file_porker_v2_domain_proto_rawDesc = "" +
	"\n" +
	"\x16porker/v2/domain.proto\x12\tporker.v2\"f\n" +
	"\x06Ballot\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12&\n" +
	"\x05point\x18\x03 \x01(\x0e2\x10.porker.v2.PointR\x05point\"\x86\x02\n" +
	"\rRoomCondition\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\"\n" +
	"\radmin_user_id\x18\x02 \x01(\tR\vadminUserId\x123\n" +
	"\n" +
	"vote_state\x18\x03 \x01(\x0e2\x14.porker.v2.VoteStateR\tvoteState\x12+\n" +
	"\aballots\x18\x04 \x03(\v2\x11.porker.v2.BallotR\aballots\x12\x1b\n" +
	"\tauto_open\x18\x05 \x01(\bR\bautoOpen\x129\n" +
	"\fdisplay_mode\x18\x06 \x01(\x0e2\x16.porker.v2.DisplayModeR\vdisplayMode*&\n" +
	"\tViolation\x12\x19\n" +
	"\x15VIOLATION_UNSPECIFIED\x10\x00*Q\n" +
	"\tVoteState\x12\x1a\n" +
	"\x16VOTE_STATE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fVOTE_STATE_HIDE\x10\x01\x12\x13\n" +
	"\x0fVOTE_STATE_OPEN\x10\x02*\\\n" +
	"\vDisplayMode\x12\x1c\n" +
	"\x18DISPLAY_MODE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12DISPLAY_MODE_POINT\x10\x01\x12\x17\n" +
	"\x13DISPLAY_MODE_TSHIRT\x10\x02*\xbd\x01\n" +
	"\x05Point\x12\x15\n" +
	"\x11POINT_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aPOINT_0\x10\x01\x12\r\n" +
	"\tPOINT_0_5\x10\x02\x12\v\n" +
	"\aPOINT_1\x10\x03\x12\v\n" +
	"\aPOINT_2\x10\x04\x12\v\n" +
	"\aPOINT_3\x10\x05\x12\v\n" +
	"\aPOINT_5\x10\x06\x12\v\n" +
	"\aPOINT_8\x10\a\x12\f\n" +
	"\bPOINT_13\x10\b\x12\f\n" +
	"\bPOINT_21\x10\t\x12\x10\n" +
	"\fPOINT_COFFEE\x10d\x12\x12\n" +
	"\x0ePOINT_QUESTION\x10eBPZNgithub.com/swallowarc/porker2/backend/internal/interface/pb/porker/v2;porkerv2b\x06proto3"

var (
	file_porker_v2_domain_proto_rawDescOnce sync.Once
	file_porker_v2_domain_proto_rawDescData []byte
)

func file_porker_v2_domain_proto_rawDescGZIP() []byte {
	file_porker_v2_domain_proto_rawDescOnce.Do(func() {
		file_porker_v2_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_porker_v2_domain_proto_rawDesc), len(file_porker_v2_domain_proto_rawDesc)))
	})
	return file_porker_v2_domain_proto_rawDescData
}

var file_porker_v2_domain_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_porker_v2_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_porker_v2_domain_proto_goTypes = []any{
	(Violation)(0),        // 0: porker.v2.Violation
	(VoteState)(0),        // 1: porker.v2.VoteState
	(DisplayMode)(0),      // 2: porker.v2.DisplayMode
	(Point)(0),            // 3: porker.v2.Point
	(*Ballot)(nil),        // 4: porker.v2.Ballot
	(*RoomCondition)(nil), // 5: porker.v2.RoomCondition
}
var file_porker_v2_domain_proto_depIdxs = []int32{
	3, // 0: porker.v2.Ballot.point:type_name -> porker.v2.Point
	1, // 1: porker.v2.RoomCondition.vote_state:type_name -> porker.v2.VoteState
	4, // 2: porker.v2.RoomCondition.ballots:type_name -> porker.v2.Ballot
	2, // 3: porker.v2.RoomCondition.display_mode:type_name -> porker.v2.DisplayMode
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_porker_v2_domain_proto_init() }
func file_porker_v2_domain_proto_init() {
	if File_porker_v2_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_porker_v2_domain_proto_rawDesc), len(file_porker_v2_domain_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_porker_v2_domain_proto_goTypes,
		DependencyIndexes: file_porker_v2_domain_proto_depIdxs,
		EnumInfos:         file_porker_v2_domain_proto_enumTypes,
		MessageInfos:      file_porker_v2_domain_proto_msgTypes,
	}.Build()
	File_porker_v2_domain_proto = out.File
	file_porker_v2_domain_proto_goTypes = nil
	file_porker_v2_domain_proto_depIdxs = nil
}
