// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: porker/v2/service.proto

package porkerv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Login ログイン
// ログインが成功した場合、tokenを返す。
//
// Errors:
// - InvalidArgument:
//   - ログイン名が未指定、またはフォーマット不正
//
// - AlreadyExists:
//   - 既に同じIDでログイン済み
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// VerifyUser ユーザの存在確認
// cookieの有効性を確認。
//
// Errors:
// - Unauthenticated:
//   - cookieのtokenがない、または無効
type VerifyUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserRequest) Reset() {
	*x = VerifyUserRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserRequest) ProtoMessage() {}

func (x *VerifyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserRequest.ProtoReflect.Descriptor instead.
func (*VerifyUserRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{2}
}

type VerifyUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName      string                 `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyUserResponse) Reset() {
	*x = VerifyUserResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyUserResponse) ProtoMessage() {}

func (x *VerifyUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyUserResponse.ProtoReflect.Descriptor instead.
func (*VerifyUserResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VerifyUserResponse) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

// Logout ログアウト
// ログアウトする。
//
// Errors:
// - Unauthenticated:
//   - cookieのtokenがない、または無効
type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{4}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{5}
}

// CreateRoom roomを作成する。
//
// Errors:
// - Unauthenticated:
//   - cookieのtokenがない、または無効
type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{6}
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRoomResponse) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// CheckRoom roomが入室可能か確認する。
//
// Errors:
// - Unauthenticated:
//   - cookieのtokenがない、または無効
//
// - NotFound:
//   - roomが存在しない
//
// - FailedPrecondition:
//   - roomが満員
type CheckRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRoomRequest) Reset() {
	*x = CheckRoomRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomRequest) ProtoMessage() {}

func (x *CheckRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomRequest.ProtoReflect.Descriptor instead.
func (*CheckRoomRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{8}
}

func (x *CheckRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type CheckRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRoomResponse) Reset() {
	*x = CheckRoomResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRoomResponse) ProtoMessage() {}

func (x *CheckRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRoomResponse.ProtoReflect.Descriptor instead.
func (*CheckRoomResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{9}
}

// JoinRoom roomに参加する。
//
// Errors:
// - Unauthenticated:
//   - cookieのtokenがない、または無効
//
// - NotFound:
//   - roomが存在しない
//
// - FailedPrecondition:
//   - roomが満員
//   - 指定されたroomに参加していない
type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{10}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *RoomCondition         `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{11}
}

func (x *JoinRoomResponse) GetCondition() *RoomCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

// LeaveRoom roomから退出する。
//
// Errors:
// - Unauthenticated:
//   - cookieのtokenがない、または無効
//
// - FailedPrecondition:
//   - 指定されたroomに参加していない
type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{12}
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type LeaveRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomResponse) Reset() {
	*x = LeaveRoomResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomResponse) ProtoMessage() {}

func (x *LeaveRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomResponse.ProtoReflect.Descriptor instead.
func (*LeaveRoomResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{13}
}

// CastVote 投票する。
//
// Errors:
// - Unauthenticated:
//   - cookieのtokenがない、または無効
//
// - FailedPrecondition:
//   - 指定されたroomに参加していない
//   - roomが投票可能な状態でない
type CastVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Point         Point                  `protobuf:"varint,2,opt,name=point,proto3,enum=porker.v2.Point" json:"point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastVoteRequest) Reset() {
	*x = CastVoteRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastVoteRequest) ProtoMessage() {}

func (x *CastVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastVoteRequest.ProtoReflect.Descriptor instead.
func (*CastVoteRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{14}
}

func (x *CastVoteRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CastVoteRequest) GetPoint() Point {
	if x != nil {
		return x.Point
	}
	return Point_POINT_UNSPECIFIED
}

type CastVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CastVoteResponse) Reset() {
	*x = CastVoteResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CastVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CastVoteResponse) ProtoMessage() {}

func (x *CastVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CastVoteResponse.ProtoReflect.Descriptor instead.
func (*CastVoteResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{15}
}

// ResetVotes 投票をリセットする。
//
// Errors:
// - Unauthenticated:
//   - cookieのtokenがない、または無効
//
// - NotFound:
//   - 指定されたroomに参加していない
type ResetVotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetVotesRequest) Reset() {
	*x = ResetVotesRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetVotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetVotesRequest) ProtoMessage() {}

func (x *ResetVotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetVotesRequest.ProtoReflect.Descriptor instead.
func (*ResetVotesRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{16}
}

func (x *ResetVotesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ResetVotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetVotesResponse) Reset() {
	*x = ResetVotesResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetVotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetVotesResponse) ProtoMessage() {}

func (x *ResetVotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetVotesResponse.ProtoReflect.Descriptor instead.
func (*ResetVotesResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{17}
}

// ShowVotes 開票する。
//
// Errors:
// - Unauthenticated:
//   - cookieのtokenがない、または無効
//
// - NotFound:
//   - 指定されたroomに参加していない
//
// - FailedPrecondition:
//   - roomが開票可能な状態でない
type ShowVotesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowVotesRequest) Reset() {
	*x = ShowVotesRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowVotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowVotesRequest) ProtoMessage() {}

func (x *ShowVotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowVotesRequest.ProtoReflect.Descriptor instead.
func (*ShowVotesRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{18}
}

func (x *ShowVotesRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

type ShowVotesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShowVotesResponse) Reset() {
	*x = ShowVotesResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShowVotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowVotesResponse) ProtoMessage() {}

func (x *ShowVotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowVotesResponse.ProtoReflect.Descriptor instead.
func (*ShowVotesResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{19}
}

// KickUser ユーザを強制退室させる。
//
// Errors:
// - Unauthenticated:
//   - cookieのtokenがない、または無効
//
// - NotFound:
//   - 実行ユーザが指定されたroomに参加していない
//
// - PermissionDenied:
//   - 実行ユーザがroomのオーナーではない
//
// - FailedPrecondition:
//   - 実行ユーザ自身のIDが指定されている
//   - target_user_idが指定されたroomに参加していない
type KickUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserRequest) Reset() {
	*x = KickUserRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserRequest) ProtoMessage() {}

func (x *KickUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserRequest.ProtoReflect.Descriptor instead.
func (*KickUserRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{20}
}

func (x *KickUserRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *KickUserRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type KickUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickUserResponse) Reset() {
	*x = KickUserResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickUserResponse) ProtoMessage() {}

func (x *KickUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickUserResponse.ProtoReflect.Descriptor instead.
func (*KickUserResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{21}
}

// UpdateRoom roomの設定を変更する。
//
// Errors:
// - Unauthenticated:
//   - cookieのtokenがない、または無効
//
// - NotFound:
//   - 指定されたroomに参加していない
type UpdateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	AutoOpen      bool                   `protobuf:"varint,2,opt,name=auto_open,json=autoOpen,proto3" json:"auto_open,omitempty"`
	DisplayMode   DisplayMode            `protobuf:"varint,3,opt,name=display_mode,json=displayMode,proto3,enum=porker.v2.DisplayMode" json:"display_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomRequest) Reset() {
	*x = UpdateRoomRequest{}
	mi := &file_porker_v2_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomRequest) ProtoMessage() {}

func (x *UpdateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoomRequest) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UpdateRoomRequest) GetAutoOpen() bool {
	if x != nil {
		return x.AutoOpen
	}
	return false
}

func (x *UpdateRoomRequest) GetDisplayMode() DisplayMode {
	if x != nil {
		return x.DisplayMode
	}
	return DisplayMode_DISPLAY_MODE_UNSPECIFIED
}

type UpdateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoomResponse) Reset() {
	*x = UpdateRoomResponse{}
	mi := &file_porker_v2_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoomResponse) ProtoMessage() {}

func (x *UpdateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_porker_v2_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoomResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoomResponse) Descriptor() ([]byte, []int) {
	return file_porker_v2_service_proto_rawDescGZIP(), []int{23}
}

var File_porker_v2_service_proto protoreflect.FileDescriptor

const file_porker_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x17porker/v2/service.proto\x12\tporker.v2\x1a\x16porker/v2/domain.proto\"+\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\"(\n" +
	"\rLoginResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x13\n" +
	"\x11VerifyUserRequest\"J\n" +
	"\x12VerifyUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tuser_name\x18\x02 \x01(\tR\buserName\"\x0f\n" +
	"\rLogoutRequest\"\x10\n" +
	"\x0eLogoutResponse\"\x13\n" +
	"\x11CreateRoomRequest\"-\n" +
	"\x12CreateRoomResponse\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"+\n" +
	"\x10CheckRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x13\n" +
	"\x11CheckRoomResponse\"*\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"J\n" +
	"\x10JoinRoomResponse\x126\n" +
	"\tcondition\x18\x01 \x01(\v2\x18.porker.v2.RoomConditionR\tcondition\"+\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x13\n" +
	"\x11LeaveRoomResponse\"R\n" +
	"\x0fCastVoteRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12&\n" +
	"\x05point\x18\x02 \x01(\x0e2\x10.porker.v2.PointR\x05point\"\x12\n" +
	"\x10CastVoteResponse\",\n" +
	"\x11ResetVotesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x14\n" +
	"\x12ResetVotesResponse\"+\n" +
	"\x10ShowVotesRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"\x13\n" +
	"\x11ShowVotesResponse\"P\n" +
	"\x0fKickUserRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\"\x12\n" +
	"\x10KickUserResponse\"\x84\x01\n" +
	"\x11UpdateRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tauto_open\x18\x02 \x01(\bR\bautoOpen\x129\n" +
	"\fdisplay_mode\x18\x03 \x01(\x0e2\x16.porker.v2.DisplayModeR\vdisplayMode\"\x14\n" +
	"\x12UpdateRoomResponse2\xe0\x06\n" +
	"\x0ePorker2Service\x12:\n" +
	"\x05Login\x12\x17.porker.v2.LoginRequest\x1a\x18.porker.v2.LoginResponse\x12=\n" +
	"\x06Logout\x12\x18.porker.v2.LogoutRequest\x1a\x19.porker.v2.LogoutResponse\x12I\n" +
	"\n" +
	"VerifyUser\x12\x1c.porker.v2.VerifyUserRequest\x1a\x1d.porker.v2.VerifyUserResponse\x12I\n" +
	"\n" +
	"CreateRoom\x12\x1c.porker.v2.CreateRoomRequest\x1a\x1d.porker.v2.CreateRoomResponse\x12F\n" +
	"\tCheckRoom\x12\x1b.porker.v2.CheckRoomRequest\x1a\x1c.porker.v2.CheckRoomResponse\x12E\n" +
	"\bJoinRoom\x12\x1a.porker.v2.JoinRoomRequest\x1a\x1b.porker.v2.JoinRoomResponse0\x01\x12F\n" +
	"\tLeaveRoom\x12\x1b.porker.v2.LeaveRoomRequest\x1a\x1c.porker.v2.LeaveRoomResponse\x12C\n" +
	"\bCastVote\x12\x1a.porker.v2.CastVoteRequest\x1a\x1b.porker.v2.CastVoteResponse\x12F\n" +
	"\tShowVotes\x12\x1b.porker.v2.ShowVotesRequest\x1a\x1c.porker.v2.ShowVotesResponse\x12I\n" +
	"\n" +
	"ResetVotes\x12\x1c.porker.v2.ResetVotesRequest\x1a\x1d.porker.v2.ResetVotesResponse\x12C\n" +
	"\bKickUser\x12\x1a.porker.v2.KickUserRequest\x1a\x1b.porker.v2.KickUserResponse\x12I\n" +
	"\n" +
	"UpdateRoom\x12\x1c.porker.v2.UpdateRoomRequest\x1a\x1d.porker.v2.UpdateRoomResponseBPZNgithub.com/swallowarc/porker2/backend/internal/interface/pb/porker/v2;porkerv2b\x06proto3"

var (
	file_porker_v2_service_proto_rawDescOnce sync.Once
	file_porker_v2_service_proto_rawDescData []byte
)

func file_porker_v2_service_proto_rawDescGZIP() []byte {
	file_porker_v2_service_proto_rawDescOnce.Do(func() {
		file_porker_v2_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_porker_v2_service_proto_rawDesc), len(file_porker_v2_service_proto_rawDesc)))
	})
	return file_porker_v2_service_proto_rawDescData
}

var file_porker_v2_service_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_porker_v2_service_proto_goTypes = []any{
	(*LoginRequest)(nil),       // 0: porker.v2.LoginRequest
	(*LoginResponse)(nil),      // 1: porker.v2.LoginResponse
	(*VerifyUserRequest)(nil),  // 2: porker.v2.VerifyUserRequest
	(*VerifyUserResponse)(nil), // 3: porker.v2.VerifyUserResponse
	(*LogoutRequest)(nil),      // 4: porker.v2.LogoutRequest
	(*LogoutResponse)(nil),     // 5: porker.v2.LogoutResponse
	(*CreateRoomRequest)(nil),  // 6: porker.v2.CreateRoomRequest
	(*CreateRoomResponse)(nil), // 7: porker.v2.CreateRoomResponse
	(*CheckRoomRequest)(nil),   // 8: porker.v2.CheckRoomRequest
	(*CheckRoomResponse)(nil),  // 9: porker.v2.CheckRoomResponse
	(*JoinRoomRequest)(nil),    // 10: porker.v2.JoinRoomRequest
	(*JoinRoomResponse)(nil),   // 11: porker.v2.JoinRoomResponse
	(*LeaveRoomRequest)(nil),   // 12: porker.v2.LeaveRoomRequest
	(*LeaveRoomResponse)(nil),  // 13: porker.v2.LeaveRoomResponse
	(*CastVoteRequest)(nil),    // 14: porker.v2.CastVoteRequest
	(*CastVoteResponse)(nil),   // 15: porker.v2.CastVoteResponse
	(*ResetVotesRequest)(nil),  // 16: porker.v2.ResetVotesRequest
	(*ResetVotesResponse)(nil), // 17: porker.v2.ResetVotesResponse
	(*ShowVotesRequest)(nil),   // 18: porker.v2.ShowVotesRequest
	(*ShowVotesResponse)(nil),  // 19: porker.v2.ShowVotesResponse
	(*KickUserRequest)(nil),    // 20: porker.v2.KickUserRequest
	(*KickUserResponse)(nil),   // 21: porker.v2.KickUserResponse
	(*UpdateRoomRequest)(nil),  // 22: porker.v2.UpdateRoomRequest
	(*UpdateRoomResponse)(nil), // 23: porker.v2.UpdateRoomResponse
	(*RoomCondition)(nil),      // 24: porker.v2.RoomCondition
	(Point)(0),                 // 25: porker.v2.Point
	(DisplayMode)(0),           // 26: porker.v2.DisplayMode
}
var file_porker_v2_service_proto_depIdxs = []int32{
	24, // 0: porker.v2.JoinRoomResponse.condition:type_name -> porker.v2.RoomCondition
	25, // 1: porker.v2.CastVoteRequest.point:type_name -> porker.v2.Point
	26, // 2: porker.v2.UpdateRoomRequest.display_mode:type_name -> porker.v2.DisplayMode
	0,  // 3: porker.v2.Porker2Service.Login:input_type -> porker.v2.LoginRequest
	4,  // 4: porker.v2.Porker2Service.Logout:input_type -> porker.v2.LogoutRequest
	2,  // 5: porker.v2.Porker2Service.VerifyUser:input_type -> porker.v2.VerifyUserRequest
	6,  // 6: porker.v2.Porker2Service.CreateRoom:input_type -> porker.v2.CreateRoomRequest
	8,  // 7: porker.v2.Porker2Service.CheckRoom:input_type -> porker.v2.CheckRoomRequest
	10, // 8: porker.v2.Porker2Service.JoinRoom:input_type -> porker.v2.JoinRoomRequest
	12, // 9: porker.v2.Porker2Service.LeaveRoom:input_type -> porker.v2.LeaveRoomRequest
	14, // 10: porker.v2.Porker2Service.CastVote:input_type -> porker.v2.CastVoteRequest
	18, // 11: porker.v2.Porker2Service.ShowVotes:input_type -> porker.v2.ShowVotesRequest
	16, // 12: porker.v2.Porker2Service.ResetVotes:input_type -> porker.v2.ResetVotesRequest
	20, // 13: porker.v2.Porker2Service.KickUser:input_type -> porker.v2.KickUserRequest
	22, // 14: porker.v2.Porker2Service.UpdateRoom:input_type -> porker.v2.UpdateRoomRequest
	1,  // 15: porker.v2.Porker2Service.Login:output_type -> porker.v2.LoginResponse
	5,  // 16: porker.v2.Porker2Service.Logout:output_type -> porker.v2.LogoutResponse
	3,  // 17: porker.v2.Porker2Service.VerifyUser:output_type -> porker.v2.VerifyUserResponse
	7,  // 18: porker.v2.Porker2Service.CreateRoom:output_type -> porker.v2.CreateRoomResponse
	9,  // 19: porker.v2.Porker2Service.CheckRoom:output_type -> porker.v2.CheckRoomResponse
	11, // 20: porker.v2.Porker2Service.JoinRoom:output_type -> porker.v2.JoinRoomResponse
	13, // 21: porker.v2.Porker2Service.LeaveRoom:output_type -> porker.v2.LeaveRoomResponse
	15, // 22: porker.v2.Porker2Service.CastVote:output_type -> porker.v2.CastVoteResponse
	19, // 23: porker.v2.Porker2Service.ShowVotes:output_type -> porker.v2.ShowVotesResponse
	17, // 24: porker.v2.Porker2Service.ResetVotes:output_type -> porker.v2.ResetVotesResponse
	21, // 25: porker.v2.Porker2Service.KickUser:output_type -> porker.v2.KickUserResponse
	23, // 26: porker.v2.Porker2Service.UpdateRoom:output_type -> porker.v2.UpdateRoomResponse
	15, // [15:27] is the sub-list for method output_type
	3,  // [3:15] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_porker_v2_service_proto_init() }
func file_porker_v2_service_proto_init() {
	if File_porker_v2_service_proto != nil {
		return
	}
	file_porker_v2_domain_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_porker_v2_service_proto_rawDesc), len(file_porker_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_porker_v2_service_proto_goTypes,
		DependencyIndexes: file_porker_v2_service_proto_depIdxs,
		MessageInfos:      file_porker_v2_service_proto_msgTypes,
	}.Build()
	File_porker_v2_service_proto = out.File
	file_porker_v2_service_proto_goTypes = nil
	file_porker_v2_service_proto_depIdxs = nil
}
