name: "バグ報告"
description: "バグを報告するためのテンプレート"
title: "[バグ] <タイトルを入力>"
labels: [ "bug", "needs-triage" ]
body:
  - type: markdown
    attributes:
      value: "## 🐛 バグの概要\nバグの詳細を記入してください。"

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "再現手順"
      description: "バグを再現する手順を記入してください。"
      placeholder: "1. 〇〇を開く\n2. △△を実行\n3. 期待した動作にならない"
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "期待する動作"
      description: "本来期待される動作を記述してください。"
      placeholder: "例: ボタンを押すとダイアログが表示されるべき"

  - type: input
    id: environment
    attributes:
      label: "環境"
      description: "使用している環境を記入してください。（OS, ブラウザ, バージョンなど）"
      placeholder: "例: Ubuntu 22.04 / Chrome 120.0"
